# -*- coding: utf-8 -*-
"""Modelagem Eletrotécnica e Simulação Dinâmica de Motores de Indução Trifásicos (MIT)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZTzNA2bt0_PppvYlk0KQerDvZD5CPQ6Q
"""

import math
import numpy as np
import matplotlib.pyplot as plt

class MotorInducao:
    """
    Classe para modelagem, determinação de parâmetros através de ensaios eletrotécnicos
    e simulação das curvas de conjugado vs. velocidade de um Motor de Indução Trifásico (MIT).
    """
    def __init__(self):
        # Dados de placa e configuração inicial
        self.classe_nema = "A"
        self.tensao_nominal = 0.0
        self.corrente_nominal = 0.0
        self.potencia_eixo_cv = 0.0
        self.freq_rede = 60.0
        self.n_polos = 4
        self.ligacao = 1  # 1 para Estrela, 2 para Triângulo

        # Parâmetros do circuito equivalente (calculados ou inseridos diretamente)
        self.r1 = 0.0
        self.r2 = 0.0
        self.x1 = 0.0
        self.x2 = 0.0
        self.xm = 0.0

        # Parâmetros de Thévenin e Grandezas Síncronas
        self.v_th = 0.0
        self.r_th = 0.0
        self.x_th = 0.0
        self.n_sinc = 0.0
        self.w_sinc = 0.0

    def ensaio_cc(self, v_cc, i_cc):
        """Calcula a resistência estatórica (R1) via ensaio de Corrente Contínua."""
        self.r1 = v_cc / (2 * i_cc)
        print(f"[Ensaio CC] R1 determinado: {self.r1:.4f} Ω")

    def ensaio_a_vazio(self, ia, ib, ic, p1, p2, v_linha):
        """Processa o ensaio a vazio para determinar a impedância de magnetização."""
        i_med = (ia + ib + ic) / 3

        # Ajuste da tensão de fase de acordo com a ligação do estator
        v_fase = v_linha / math.sqrt(3) if self.ligacao == 1 else v_linha

        # Impedância de vazio por fase
        z_vz = v_fase / i_med

        # Perdas no cobre do estator durante o ensaio
        p_c_estator = 3 * (i_med ** 2) * self.r1
        p_rotacionais = (p1 + p2) - p_c_estator

        # Aproximação clássica: Xm + X1 ≈ Zvz
        self._z_vz_temp = z_vz
        print(f"[Ensaio a Vazio] Impedância equivalente de vazio: {z_vz:.4f} Ω")
        print(f"[Ensaio a Vazio] Perdas rotacionais estimadas: {p_rotacionais:.2f} W")

    def ensaio_rotor_bloqueado(self, ia, ib, ic, p1, p2, v_linha_bloq, freq_ensaio):
        """
        Processa o ensaio de rotor bloqueado.
        Aplica a correção de frequência para reatâncias e separa X1 e X2 com base na classe NEMA.
        """
        i_med_b = (ia + ib + ic) / 3
        p_total = p1 + p2

        # Impedância de curto-circuito (rotor bloqueado)
        z_rb = v_linha_bloq / (math.sqrt(3) * i_med_b)

        # Fator de potência no ensaio
        fp_rb = p_total / (math.sqrt(3) * v_linha_bloq * i_med_b)
        theta = math.acos(clip_val(fp_rb, -1.0, 1.0))

        r_rb = z_rb * math.cos(theta)
        x_rb_freq_ensaio = z_rb * math.sin(theta)

        # Determinação de R2 referida ao estator
        self.r2 = r_rb - self.r1

        # Correção da reatância para a frequência nominal da rede
        x_rb_nominal = (self.freq_rede / freq_ensaio) * x_rb_freq_ensaio

        # Divisão das reatâncias de dispersão conforme a Classe de Projeto NEMA
        classes_nema = {
            "Rotor Bloqueado": (0.5, 0.5),
            "A": (0.5, 0.5),
            "B": (0.4, 0.6),
            "C": (0.3, 0.7),
            "D": (0.5, 0.5)
        }

        fator_x1, fator_x2 = classes_nema.get(self.classe_nema, (0.5, 0.5))
        self.x1 = fator_x1 * x_rb_nominal
        self.x2 = fator_x2 * x_rb_nominal

        # Recupera o Zvz do ensaio a vazio para isolar a reatância de magnetização (Xm)
        if hasattr(self, '_z_vz_temp'):
            self.xm = self._z_vz_temp - self.x1

        print(f"[Ensaio RB] R2 calculado: {self.r2:.4f} Ω")
        print(f"[Ensaio RB] X1: {self.x1:.4f} Ω | X2: {self.x2:.4f} Ω (Classe NEMA {self.classe_nema})")
        print(f"[Ensaio RB] Xm isolado: {self.xm:.4f} Ω")

        # Calcula os equivalentes de Thévenin após consolidar os parâmetros
        self.calcular_equivalente_thevenin()

    def calcular_equivalente_thevenin(self):
        """Calcula o circuito equivalente de Thévenin exato visto do rotor utilizando números complexos."""
        v_fase = self.tensao_nominal / math.sqrt(3) if self.ligacao == 1 else self.tensao_nominal

        # Impedância de Thévenin usando formulação complexa exata
        z_thevenin = (1j * self.xm * (self.r1 + 1j * self.x1)) / (self.r1 + 1j * (self.x1 + self.xm))
        self.r_th = z_thevenin.real
        self.x_th = z_thevenin.imag

        # Magnitude da tensão de Thévenin
        self.v_th = (self.xm / (self.x1 + self.xm)) * v_fase

        # Velocidades de sincronismo
        self.n_sinc = (120 * self.freq_rede) / self.n_polos
        self.w_sinc = self.n_sinc * np.pi / 30

    def calcular_torque_induzido(self, escorregamento, r2_atual):
        """Equação analítica do torque induzido em função do escorregamento e do R2."""
        escorregamento = np.where(escorregamento == 0, 0.001, escorregamento)

        termo_numerador = (3 * (self.v_th ** 2) * r2_atual) / escorregamento
        termo_denominador = self.w_sinc * (((self.r_th + r2_atual / escorregamento) ** 2) + ((self.x_th + self.x2) ** 2))
        return termo_numerador / termo_denominador

    def exibir_parametros(self):
        """Imprime os parâmetros identificados do circuito equivalente."""
        print("\n" + "="*40)
        print("     PARÂMETROS IDENTIFICADOS DO MIT     ")
        print("="*40)
        print(f"R1 (Estator)        : {self.r1:.4f} Ω")
        print(f"R2 (Rotor Ref.)     : {self.r2:.4f} Ω")
        print(f"X1 (Dispersão Est.) : {self.x1:.4f} Ω")
        print(f"X2 (Dispersão Rot.) : {self.x2:.4f} Ω")
        print(f"Xm (Magnetização)   : {self.xm:.4f} Ω")
        print("-"*40)
        print(f"Vth (Thévenin)      : {self.v_th:.2f} V")
        print(f"Rth (Thévenin)      : {self.r_th:.4f} Ω")
        print(f"Xth (Thévenin)      : {self.x_th:.4f} Ω")
        print("="*40)

    def simular_e_plotar_curvas(self):
        """Calcula pontos críticos de operação e plota o gráfico comparativo de variação de R2."""
        if self.w_sinc == 0:
            self.calcular_equivalente_thevenin()

        s_max_torque = self.r2 / (math.sqrt(self.r_th**2 + (self.x_th + self.x2)**2))
        n_max_torque = (1 - s_max_torque) * self.n_sinc
        t_max = 3 * (self.v_th ** 2) / (2 * self.w_sinc * (self.r_th + math.sqrt(self.r_th**2 + (self.x_th + self.x2)**2)))
        t_partida = self.calcular_torque_induzido(1.0, self.r2)

        print("\n" + "-"*40)
        print("     PONTOS CRÍTICOS (R2 ORIGINAL)     ")
        print("-"*40)
        print(f"Escorregamento Máximo Torque : {s_max_torque:.4f}")
        print(f"Velocidade do Torque Máximo  : {n_max_torque:.2f} RPM")
        print(f"Torque Máximo (Breakdown)    : {t_max:.2f} N.m")
        print(f"Torque de Partida (Instante) : {t_partida:.2f} N.m")
        print("-"*40)

        s_vetor = np.arange(0.001, 1.2, 0.001)
        rpm_vetor = (1 - s_vetor) * self.n_sinc

        t_original = self.calcular_torque_induzido(s_vetor, self.r2)
        t_2x = self.calcular_torque_induzido(s_vetor, 2 * self.r2)
        t_5x = self.calcular_torque_induzido(s_vetor, 5 * self.r2)

        plt.figure(figsize=(10, 6))
        plt.plot(rpm_vetor, t_original, label='R₂ Original', color='black', linewidth=2)
        plt.plot(rpm_vetor, t_2x, label='R₂ Ampliado 2x', linestyle='--', linewidth=1.8)
        plt.plot(rpm_vetor, t_5x, label='R₂ Ampliado 5x', linestyle=':', linewidth=1.8)

        plt.xlabel('Velocidade Mecânica $n_m$ (RPM)', fontsize=11)
        plt.ylabel('Torque Induzido $\\tau_{ind}$ (N·m)', fontsize=11)
        plt.title('Curva Característica: Conjugado vs. Velocidade do MIT', fontsize=12, fontweight='bold')
        plt.grid(True, which='both', linestyle=':', alpha=0.6)
        plt.axhline(0, color='black', linewidth=0.8)
        plt.axvline(self.n_sinc, color='red', linestyle='--', alpha=0.7, label=f'Velocidade Síncrona ({self.n_sinc:.0f} RPM)')

        plt.xlim(0, self.n_sinc * 1.1)
        plt.ylim(0, t_max * 1.1)
        plt.legend(loc='upper right', frameon=True)
        plt.show()

def clip_val(val, min_val, max_val):
    return max(min_val, min(val, max_val))


if __name__ == "__main__":
    motor = MotorInducao()

    print("="*55)
    print(" SISTEMA DE ANÁLISE DE MOTORES DE INDUÇÃO TRIFÁSICOS ")
    print("="*55)

    while True:
        print("\n[1] Iniciar Nova Análise (Dados de Placa)\n[2] Executar com Dados Padrão de Laboratório\n[3] Sair")
        opcao_menu = input("Escolha uma opção: ")

        if opcao_menu == "3":
            print("Encerrando software de simulação.")
            break

        elif opcao_menu == "2":
            # --- HIGHLIGHT: CONFIGURAÇÃO DOS DADOS PADRÃO DE LABORATÓRIO ---
            motor.tensao_nominal = 460.0
            motor.ligacao = 1              # 1 = Estrela
            motor.corrente_nominal = 28.0
            motor.potencia_eixo_cv = 25.0
            motor.freq_rede = 60.0
            motor.n_polos = 4
            motor.classe_nema = "A"

            print("\n" + "="*50)
            print("   DADOS PADRÃO DE LABORATÓRIO CARREGADOS (OPÇÃO 2)   ")
            print("="*50)
            print(f"• Dados de Placa: {motor.tensao_nominal}V | {motor.corrente_nominal}A | {motor.potencia_eixo_cv}CV | {motor.n_polos} Polos | Classe {motor.classe_nema}")
            print("• Ensaio CC     : Vcc = 13.6 V, Icc = 28.0 A")
            print("• Ensaio Vazio  : Ia = 8.12 A, Ib = 8.20 A, Ic = 8.18 A | P1 = 420.0 W, P2 = 0.0 W")
            print("• Ensaio Rotor B: Ia = 28.1 A, Ib = 28.0 A, Ic = 27.6 A | P1 = 920.0 W, P2 = 0.0 W")
            print("                  V_bloqueio = 25.0 V | Freq_ensaio = 15.0 Hz")
            print("="*50 + "\n")

            # Processamento sequencial dos ensaios com os presets destacados
            motor.ensaio_cc(v_cc=13.6, i_cc=28.0)
            motor.ensaio_a_vazio(ia=8.12, ib=8.20, ic=8.18, p1=420.0, p2=0.0, v_linha=460.0)
            motor.ensaio_rotor_bloqueado(ia=28.1, ib=28.0, ic=27.6, p1=920.0, p2=0.0, v_linha_bloq=25.0, freq_ensaio=15.0)

            motor.exibir_parametros()
            motor.simular_e_plotar_curvas()
            break

        elif opcao_menu == "1":
            motor.tensao_nominal = float(input("Tensão Nominal de Linha (V): "))
            motor.ligacao = int(input("Ligação do Motor - Estrela [1] ou Triângulo [2]: "))
            motor.corrente_nominal = float(input("Corrente Nominal (A): "))
            motor.potencia_eixo_cv = float(input("Potência no Eixo (CV): "))
            motor.freq_rede = float(input("Frequência da Rede (Hz): "))
            motor.n_polos = int(input("Número de Polos: "))
            motor.classe_nema = input("Classe de Isolação/Projeto NEMA (A, B, C ou D): ").upper()

            while True:
                print("\n--- Menu de Ensaios Elétricos ---")
                print("1. Executar Ensaio CC")
                print("2. Executar Ensaio a Vazio")
                print("3. Executar Ensaio de Rotor Bloqueado")
                print("4. Exibir Parâmetros Circutais")
                print("5. Plotar Curva Conjugado-Velocidade Completa")
                print("6. Voltar ao menu principal")

                opc = input("Selecione a rotina experimental correspondente: ")

                if opc == "1":
                    v_cc = float(input("Tensão CC aplicada medida (V): "))
                    i_cc = float(input("Corrente CC injetada média (A): "))
                    motor.ensaio_cc(v_cc, i_cc)
                elif opc == "2":
                    ia = float(input("Ia (A): "))
                    ib = float(input("Ib (A): "))
                    ic = float(input("Ic (A): "))
                    p1 = float(input("Potência do Wattímetro 1 (W): "))
                    p2 = float(input("Potência do Wattímetro 2 (W): "))
                    motor.ensaio_a_vazio(ia, ib, ic, p1, p2, motor.tensao_nominal)
                elif opc == "3":
                    ia = float(input("Ia (A): "))
                    ib = float(input("Ib (A): "))
                    ic = float(input("Ic (A): "))
                    p1 = float(input("Potência Wattímetro 1 (W): "))
                    p2 = float(input("Potência Wattímetro 2 (W): "))
                    v_bloq = float(input("Tensão de linha reduzida aplicada (V): "))
                    f_ensaio = float(input("Frequência reduzida utilizada no ensaio (Hz): "))
                    motor.ensaio_rotor_bloqueado(ia, ib, ic, p1, p2, v_bloq, f_ensaio)
                elif opc == "4":
                    motor.exibir_parametros()
                elif opc == "5":
                    motor.simular_e_plotar_curvas()
                elif opc == "6":
                    break
        else:
            print("Opção inválida!")